sudo: false

language: elixir
elixir:
  - 1.1.1
  - 1.2.0
otp_release:
  - 17.5
  - 18.0
  - 18.1
  - 18.2

matrix:
  exclude:
    # Elixir 1.2 requires OTP 18+
    - elixir: 1.2.0
      otp_release: 17.5
